### ISSUE TITLE
An error about 'ModuleNotFoundError: No module named 'geobench_exp.experiment''

### ISSUE THREAD

**Issue by Chenshuaiyu1120** [ServiceNow/geo-bench-experiments#3]
Hi, when I follow the Installation's guide to using this code. I found there has something wrong about the source code in package geobench_exp. Because there don't have the file or package named experiment and can not normal operation.I would like to inquire if there is a solution to this problem. It would appreciate it if you could help me. Many thanks.

**Comment by Carina02** [comment]
Got same problem. The geobench_exp.experiment is in another branch. For unknown reason the two branches are not unified(e.g., the config files are written in different formats). It would be appreciated that authors could fix it.

**Comment by nilsleh** [comment]
@Chenshuaiyu1120  @Carina02 apologies, somehow I don't receive notifications for new issues on this repo. You are indeed right, there was a missing file. I have updated the `main` branch and can now run experiments when cloning the repo from scratch. Please let me know if it also works on your side.
